import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import Header from "./header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CifradoEdu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>
        <Header />
        <div className="flex-1">
          {children}
        </div>
        <Toaster />
        <footer className="flex flex-col sm:flex-row justify-between items-center py-6 w-full px-4 md:px-6 border-t">
          <div className="text-center sm:text-left">
            <p className="text-xs text-muted-foreground">© 2024 CifradoEdu. Todos los derechos reservados.</p>
          </div>

          <div className="flex flex-col sm:flex-row sm:items-center sm:space-x-6 text-center sm:text-right space-y-2 sm:space-y-0">
            <p>José de Jesús Vargas Esparza</p>
            <p>Ing. Desarrollo y Gestión de Software</p>
            <p>7° &quot;B&quot;</p>
          </div>
        </footer>

      </body>
    </html>
  );
}
